eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      default-zone: http://localhost:8761

microservice:
  user-service:
    endpoints:
      endpoint:
        uri: http://SUBSCRIPTION-SERVICE/subscriptionService/getSubscription/
